#!/bin/sh

# Test if executed as root
if [ "$(id -u)" = "0" ]; then
	echo "This script must not be run as root" 1>&2
	exit 1
fi
# home="$(getent passwd $SUDO_USER | cut -d: -f6)"
home=~

copy_files() {
	mkdir -p $home/.local/bin/
	cp -r change_proxy $home/.local/bin/
	chmod +x $home/.local/bin/change_proxy
	chmod +x uninstall_proxy_cmd
	mkdir -p $home/.local/share/bash-completion/completions
	# echo "for bcfile in ~/.bash_completion.d/* ; do\n  . $bcfile\ndone" >> $home/.bash_completion

	cp -r proxy_completion $home/.local/share/bash-completion/completions
	mv $home/.local/share/bash-completion/completions/proxy_completion $home/.local/share/bash-completion/completions/change_proxy
	chmod +x $home/.local/share/bash-completion/completions/change_proxy
}

echo "Updating scripts..."
copy_files
echo "Done"