#!/bin/sh

# Test if executed as root
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

copy_files() {
	mkdir /usr/local/bin
	mkdir /usr/local/etc
	mkdir /usr/local/etc/bash_completion.d/
	cp -r change_proxy /usr/local/bin/
	chmod +x /usr/local/bin/change_proxy
	chmod +x uninstall_proxy_cmd
	cp -r proxy_completion /usr/local/etc/bash_completion.d/
	chmod +x /usr/local/etc/bash_completion.d/proxy_completion
}

echo "Updating scripts..."
copy_files
echo "Done"