#!/bin/sh

# Test if executed as root
if [ "$(id -u)" = "0" ]; then
	echo "This script sould not be run as root" 1>&2
	exit 1
fi
# home="$(getent passwd $SUDO_USER | cut -d: -f6)"
home=~

delete_files() {
	rm -f $home/.local/bin/change_proxy
	rm -f $home/.local/share/bash-completion/completions/change_proxy
}

echo "Deleting scripts..."
delete_files
echo "Done"